In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from bs4 import BeautifulSoup
import time
import re

In [ ]:
driver = webdriver.Firefox()
url = 'https://www.carsome.id/beli-mobil-bekas'
driver.get(url)
soup_list = []

while True:
    try:
        next = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "//button[@class='v-pagination__navigation' and @aria-label='Next page']")))
        if 'a-disabled' in next.get_attribute('class'):
            break
        next.click()
    except Exception as e:
        print(f"An error occurred: {e}")
        break

    time.sleep(5)  # Add a delay to allow the page to load
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    soup_list.append(soup)

# Close the browser when done
driver.quit()

In [149]:
car = []

for html in soup_list:
    links = html.find_all("div", class_="mod-card__footer")
    # Loop through the list of links
    for link in links:
        car_detail = {}  # Create a new car_detail dictionary for each car
        
        # Extract the text from all <p> elements within the link
        title_parts = link.find_all("p")
        title = " ".join(part.get_text(strip=True) for part in title_parts)
        car_detail['name'] = re.sub(r'\s+', ' ', title)

        # Search for details within the context of the specific car listing (using 'link')
        details1 = link.find("div", class_="mod-card__car-other")
        car_detail1 = [span.get_text(strip=True) for span in details1.find_all("span")]
        car_detail['detail1'] = car_detail1

        details2 = link.find("div", class_="mod-card__high-tag-list")
        car_detail2 = [span.get_text(strip=True) for span in details2.find_all("span")]
        car_detail['detail2'] = car_detail2

        price = link.find("div", class_="mod-card__price__total")
        price = price.text.strip()
        car_detail['price'] = re.sub(r'\s+', ' ', price)

        price = link.find("div", class_="mod-card__price")
        price = price.text.strip()
        car_detail['price'] = re.sub(r'\s+', ' ', price)

        price_m = link.find("div", class_="mod-card__price")
        price_m = "".join(price_m.get_text(strip=True) for price_m in price_m.find_all("span"))
        car_detail['monthly'] = re.sub(r'\s+', ' ', price_m)

        # Append the car_detail dictionary to the car list
        car.append(car_detail)

    # Print or use the 'car' list containing all car details
    print(price_m)

Rp 2,38 jt/bln
Rp 4,16 jt/bln
Rp 6,83 jt/bln
Rp 8,68 jt/bln
Rp 4,26 jt/bln
Rp 3,67 jt/bln
Rp 4,87 jt/bln
Rp 2,00 jt/bln
Rp 4,28 jt/bln
Rp 3,44 jt/bln
Rp 5,34 jt/bln
Rp 2,06 jt/bln
Rp 8,72 jt/bln
Rp 2,91 jt/bln
Rp 3,69 jt/bln
Rp 3,55 jt/bln
Rp 3,65 jt/bln
Rp 6,50 jt/bln
Rp 4,03 jt/bln
Rp 6,46 jt/bln
Rp 3,34 jt/bln
Rp 4,26 jt/bln
Rp 3,57 jt/bln
Rp 4,50 jt/bln
Rp 2,73 jt/bln
Rp 2,57 jt/bln
Rp 4,52 jt/bln
Rp 2,65 jt/bln
Rp 2,20 jt/bln
Rp 4,52 jt/bln
Rp 3,61 jt/bln
Rp 2,49 jt/bln
Rp 2,47 jt/bln
Rp 3,04 jt/bln

In [151]:
len(car)

610

In [152]:
car

[{'name': '2018 Daihatsu AYLA X 1.2',
  'detail1': ['10.508 km', 'Manual', 'Jakarta Utara'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah'],
  'price': 'Rp 101.000.000 Rp 2,06 jt/bln',
  'monthly': 'Rp 2,06 jt/bln'},
 {'name': '2015 Toyota AGYA TRD SPORTIVO 1.0',
  'detail1': ['112.888 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 82.000.000 Rp 1,67 jt/bln',
  'monthly': 'Rp 1,67 jt/bln'},
 {'name': '2015 Nissan X-TRAIL 2.5',
  'detail1': ['118.429 km', 'Automatic', 'Surabaya'],
  'detail2': ['Plat Ganjil', '360 Camera View', 'Keyless Push Start'],
  'price': 'Rp 169.000.000 Rp 3,44 jt/bln',
  'monthly': 'Rp 3,44 jt/bln'},
 {'name': '2020 Toyota YARIS S TRD 1.5',
  'detail1': ['15.945 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah', 'Paddle Shift'],
  'price': 'Rp 218.000.000 Rp 4,44 jt/bln',
  'monthly': 'Rp 4,44 jt/bln'},
 {'name': '2019 Toyota AGYA G 1.2',
  'detail1': ['30.404 km', 'Manual', 'Jakarta Barat'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 117.000.000 Rp 2,38 jt/bln',
  'monthly': 'Rp 2,38 jt/bln'},
 {'name': '2021 Toyota AVANZA G 1.3',
  'detail1': ['17.306 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah', 'Retract Mirror'],
  'price': 'Rp 180.000.000 Rp 3,67 jt/bln',
  'monthly': 'Rp 3,67 jt/bln'},
 {'name': '2022 Toyota AVANZA G 1.5',
  'detail1': ['12.211 km', 'Manual', 'Surabaya'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah', 'Retract Mirror'],
  'price': 'Rp 211.000.000 Rp 4,30 jt/bln',
  'monthly': 'Rp 4,30 jt/bln'},
 {'name': '2016 Mitsubishi OUTLANDER SPORT PX 2.0',
  'detail1': ['126.885 km', 'Automatic', 'Bekasi'],
  'detail2': ['Plat Genap', 'Panoramic Sun Roof', 'Auto Retract Mirror'],
  'price': 'Rp 190.000.000 Rp 3,87 jt/bln',
  'monthly': 'Rp 3,87 jt/bln'},
 {'name': '2019 Honda BRIO SATYA E 1.2',
  'detail1': ['33.464 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 140.000.000 Rp 2,85 jt/bln',
  'monthly': 'Rp 2,85 jt/bln'},
 {'name': '2021 Honda HR-V S 1.5',
  'detail1': ['33.364 km', 'Automatic', 'Malang'],
  'detail2': ['Plat Ganjil', 'Electric Parking Brake', 'Retract Mirror'],
  'price': 'Rp 248.000.000 Rp 5,05 jt/bln',
  'monthly': 'Rp 5,05 jt/bln'},
 {'name': '2018 Toyota AGYA G TRD 1.2',
  'detail1': ['44.969 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 117.000.000 Rp 2,38 jt/bln',
  'monthly': 'Rp 2,38 jt/bln'},
 {'name': '2019 Daihatsu AYLA R 1.2',
  'detail1': ['43.292 km', 'Manual', 'Depok'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 114.000.000 Rp 2,32 jt/bln',
  'monthly': 'Rp 2,32 jt/bln'},
 {'name': '2019 Daihatsu AYLA R 1.2',
  'detail1': ['57.385 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 110.000.000 Rp 2,24 jt/bln',
  'monthly': 'Rp 2,24 jt/bln'},
 {'name': '2017 Daihatsu AYLA R DLX 1.2',
  'detail1': ['53.151 km', 'Automatic', 'Jakarta Selatan'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 115.000.000 Rp 2,34 jt/bln',
  'monthly': 'Rp 2,34 jt/bln'},
 {'name': '2019 Toyota AGYA G TRD 1.2',
  'detail1': ['46.182 km', 'Manual', 'Jakarta Utara'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 118.000.000 Rp 2,40 jt/bln',
  'monthly': 'Rp 2,40 jt/bln'},
 {'name': '2019 Wuling ALMAZ LT LUX 1.5',
  'detail1': ['58.152 km', 'Automatic', 'Malang'],
  'detail2': ['Plat Genap', 'Auto Retract Mirror', 'Panoramic Sun Roof'],
  'price': 'Rp 198.000.000 Rp 4,03 jt/bln',
  'monthly': 'Rp 4,03 jt/bln'},
 {'name': '2015 Daihatsu TERIOS TX 1.5',
  'detail1': ['118.704 km', 'Manual', 'Depok'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Map Navigator'],
  'price': 'Rp 141.000.000 Rp 2,87 jt/bln',
  'monthly': 'Rp 2,87 jt/bln'},
 {'name': '2018 Toyota AGYA G TRD 1.2',
  'detail1': ['78.385 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 117.000.000 Rp 2,38 jt/bln',
  'monthly': 'Rp 2,38 jt/bln'},
 {'name': '2018 Honda MOBILIO E 1.5',
  'detail1': ['45.376 km', 'Manual', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 155.000.000 Rp 3,16 jt/bln',
  'monthly': 'Rp 3,16 jt/bln'},
 {'name': '2018 Daihatsu AYLA R 1.2',
  'detail1': ['37.343 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 108.000.000 Rp 2,20 jt/bln',
  'monthly': 'Rp 2,20 jt/bln'},
 {'name': '2019 Honda BRIO RS 1.2',
  'detail1': ['65.278 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Kamera Mundur', 'Retract Mirror', 'Sports Mode'],
  'price': 'Rp 168.000.000 Rp 3,42 jt/bln',
  'monthly': 'Rp 3,42 jt/bln'},
 {'name': '2017 Daihatsu AYLA R 1.2',
  'detail1': ['61.937 km', 'Manual', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 105.500.000 Rp 2,15 jt/bln',
  'monthly': 'Rp 2,15 jt/bln'},
 {'name': '2018 Daihatsu AYLA R 1.2',
  'detail1': ['47.085 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 111.000.000 Rp 2,26 jt/bln',
  'monthly': 'Rp 2,26 jt/bln'},
 {'name': '2022 Suzuki ERTIGA GL 1.5',
  'detail1': ['178 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah'],
  'price': 'Rp 190.000.000 Rp 3,87 jt/bln',
  'monthly': 'Rp 3,87 jt/bln'},
 {'name': '2019 Daihatsu AYLA R 1.2',
  'detail1': ['10.301 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah'],
  'price': 'Rp 114.000.000 Rp 2,32 jt/bln',
  'monthly': 'Rp 2,32 jt/bln'},
 {'name': '2017 Honda CR-V TURBO 1.5',
  'detail1': ['75.302 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Genap', 'Electric Parking Brake', 'Keyless Push Start'],
  'price': 'Rp 340.000.000 Rp 6,93 jt/bln',
  'monthly': 'Rp 6,93 jt/bln'},
 {'name': '2020 Wuling CONFERO 2WD 1.5',
  'detail1': ['18.298 km', 'Manual', 'Malang'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah'],
  'price': 'Rp 101.500.000 Rp 2,07 jt/bln',
  'monthly': 'Rp 2,07 jt/bln'},
 {'name': '2019 Wuling ALMAZ LT LUX 1.5',
  'detail1': ['50.387 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil', 'Auto Retract Mirror', 'Panoramic Sun Roof'],
  'price': 'Rp 202.000.000 Rp 4,12 jt/bln',
  'monthly': 'Rp 4,12 jt/bln'},
 {'name': '2019 Nissan LIVINA VL 1.5',
  'detail1': ['64.235 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 197.000.000 Rp 4,01 jt/bln',
  'monthly': 'Rp 4,01 jt/bln'},
 {'name': '2021 Toyota CALYA G 1.2',
  'detail1': ['44.473 km', 'Automatic', 'Bandung'],
  'detail2': ['Plat Genap', 'Retract Mirror'],
  'price': 'Rp 138.000.000 Rp 2,81 jt/bln',
  'monthly': 'Rp 2,81 jt/bln'},
 {'name': '2018 Honda BRIO SATYA E 1.2',
  'detail1': ['24.577 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 135.000.000 Rp 2,75 jt/bln',
  'monthly': 'Rp 2,75 jt/bln'},
 {'name': '2019 Daihatsu TERIOS R 1.5',
  'detail1': ['42.320 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 193.000.000 Rp 3,93 jt/bln',
  'monthly': 'Rp 3,93 jt/bln'},
 {'name': '2015 Toyota AVANZA G 1.3',
  'detail1': ['81.158 km', 'Manual', 'Surabaya'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 127.000.000 Rp 2,59 jt/bln',
  'monthly': 'Rp 2,59 jt/bln'},
 {'name': '2018 Honda HR-V S 1.5',
  'detail1': ['64.753 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Electric Parking Brake'],
  'price': 'Rp 208.000.000 Rp 4,24 jt/bln',
  'monthly': 'Rp 4,24 jt/bln'},
 {'name': '2019 Mitsubishi XPANDER ULTIMATE 1.5',
  'detail1': ['72.887 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Auto Cruise Control'],
  'price': 'Rp 216.000.000 Rp 4,40 jt/bln',
  'monthly': 'Rp 4,40 jt/bln'},
 {'name': '2018 Mitsubishi XPANDER ULTIMATE 1.5',
  'detail1': ['77.425 km', 'Automatic', 'Bandung'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 204.000.000 Rp 4,16 jt/bln',
  'monthly': 'Rp 4,16 jt/bln'},
 {'name': '2016 Daihatsu AYLA X 1.0',
  'detail1': ['63.175 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 89.000.000 Rp 1,81 jt/bln',
  'monthly': 'Rp 1,81 jt/bln'},
 {'name': '2020 Toyota AGYA G TRD 1.2',
  'detail1': ['43.689 km', 'Manual', 'Depok'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 123.000.000 Rp 2,51 jt/bln',
  'monthly': 'Rp 2,51 jt/bln'},
 {'name': '2019 Daihatsu AYLA X 1.2',
  'detail1': ['85.583 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 107.000.000 Rp 2,18 jt/bln',
  'monthly': 'Rp 2,18 jt/bln'},
 {'name': '2020 Toyota CALYA G 1.2',
  'detail1': ['54.512 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Genap', 'Retract Mirror'],
  'price': 'Rp 133.000.000 Rp 2,71 jt/bln',
  'monthly': 'Rp 2,71 jt/bln'},
 {'name': '2019 Honda HR-V E 1.5',
  'detail1': ['35.177 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil', 'Electric Parking Brake', 'Keyless Push Start'],
  'price': 'Rp 248.000.000 Rp 5,05 jt/bln',
  'monthly': 'Rp 5,05 jt/bln'},
 {'name': '2018 Mitsubishi OUTLANDER SPORT PX 2.0',
  'detail1': ['57.230 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil', 'Kamera Mundur', 'Retract Mirror'],
  'price': 'Rp 228.000.000 Rp 4,65 jt/bln',
  'monthly': 'Rp 4,65 jt/bln'},
 {'name': '2014 Mitsubishi OUTLANDER SPORT GLS 2.0',
  'detail1': ['133.127 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Ganjil', 'Sports Mode'],
  'price': 'Rp 157.000.000 Rp 3,20 jt/bln',
  'monthly': 'Rp 3,20 jt/bln'},
 {'name': '2019 Honda BRIO SATYA E 1.2',
  'detail1': ['34.815 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 142.000.000 Rp 2,89 jt/bln',
  'monthly': 'Rp 2,89 jt/bln'},
 {'name': '2016 Toyota AVANZA G 1.3',
  'detail1': ['98.478 km', 'Manual', 'Jakarta Barat'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 143.000.000 Rp 2,91 jt/bln',
  'monthly': 'Rp 2,91 jt/bln'},
 {'name': '2016 Mitsubishi OUTLANDER SPORT PX 2.0',
  'detail1': ['91.926 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Panoramic Sun Roof'],
  'price': 'Rp 195.000.000 Rp 3,97 jt/bln',
  'monthly': 'Rp 3,97 jt/bln'},
 {'name': '2018 Honda HR-V SE 1.5',
  'detail1': ['62.209 km', 'Automatic', 'Bekasi'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Paddle Shift'],
  'price': 'Rp 254.000.000 Rp 5,18 jt/bln',
  'monthly': 'Rp 5,18 jt/bln'},
 {'name': '2019 Wuling ALMAZ S+T 1.5',
  'detail1': ['76.950 km', 'Automatic', 'Bandung'],
  'detail2': ['Plat Genap', 'Electric Parking Brake', 'Kamera Mundur'],
  'price': 'Rp 199.000.000 Rp 4,05 jt/bln',
  'monthly': 'Rp 4,05 jt/bln'},
 {'name': '2018 Suzuki IGNIS GL 1.2',
  'detail1': ['43.945 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Ganjil', 'Kamera Mundur'],
  'price': 'Rp 111.500.000 Rp 2,27 jt/bln',
  'monthly': 'Rp 2,27 jt/bln'},
 {'name': '2019 Wuling ALMAZ S+T 1.5',
  'detail1': ['27.804 km', 'Automatic', 'Bandung'],
  'detail2': ['Plat Ganjil', 'Sports Mode', 'Kamera Mundur'],
  'price': 'Rp 203.000.000 Rp 4,14 jt/bln',
  'monthly': 'Rp 4,14 jt/bln'},
 {'name': '2018 Daihatsu AYLA R 1.2',
  'detail1': ['85.184 km', 'Automatic', 'Jakarta Pusat'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 117.000.000 Rp 2,38 jt/bln',
  'monthly': 'Rp 2,38 jt/bln'},
 {'name': '2019 Daihatsu TERIOS R 1.5',
  'detail1': ['40.717 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap', 'Keyless Push Start', 'Retract Mirror'],
  'price': 'Rp 193.000.000 Rp 3,93 jt/bln',
  'monthly': 'Rp 3,93 jt/bln'},
 {'name': '2019 Mitsubishi XPANDER ULTIMATE 1.5',
  'detail1': ['63.130 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Auto Cruise Control'],
  'price': 'Rp 213.000.000 Rp 4,34 jt/bln',
  'monthly': 'Rp 4,34 jt/bln'},
 {'name': '2017 Honda CR-V TURBO 1.5',
  'detail1': ['64.558 km', 'Automatic', 'Jakarta Selatan'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Paddle Shift'],
  'price': 'Rp 335.000.000 Rp 6,83 jt/bln',
  'monthly': 'Rp 6,83 jt/bln'},
 {'name': '2018 Honda HR-V SE 1.5',
  'detail1': ['43.740 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Paddle Shift'],
  'price': 'Rp 255.000.000 Rp 5,20 jt/bln',
  'monthly': 'Rp 5,20 jt/bln'},
 {'name': '2017 Toyota KIJANG INNOVA REBORN G 2.0',
  'detail1': ['51.254 km', 'Manual', 'Jakarta Barat'],
  'detail2': ['Plat Genap', 'Sports Mode'],
  'price': 'Rp 242.000.000 Rp 4,93 jt/bln',
  'monthly': 'Rp 4,93 jt/bln'},
 {'name': '2016 Honda MOBILIO RS 1.5',
  'detail1': ['84.060 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Genap', 'Sports Mode', 'Kamera Mundur'],
  'price': 'Rp 155.000.000 Rp 3,16 jt/bln',
  'monthly': 'Rp 3,16 jt/bln'},
 {'name': '2014 Toyota KIJANG INNOVA V 2.0',
  'detail1': ['87.616 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 193.000.000 Rp 3,93 jt/bln',
  'monthly': 'Rp 3,93 jt/bln'},
 {'name': '2019 Toyota AGYA G TRD 1.2',
  'detail1': ['53.576 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 122.000.000 Rp 2,49 jt/bln',
  'monthly': 'Rp 2,49 jt/bln'},
 {'name': '2016 Toyota KIJANG INNOVA G 2.0',
  'detail1': ['74.730 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil', 'Sports Mode'],
  'price': 'Rp 233.000.000 Rp 4,75 jt/bln',
  'monthly': 'Rp 4,75 jt/bln'},
 {'name': '2017 Suzuki IGNIS GL 1.2',
  'detail1': ['79.289 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 110.000.000 Rp 2,24 jt/bln',
  'monthly': 'Rp 2,24 jt/bln'},
 {'name': '2022 Toyota AGYA GR SPORT 1.2',
  'detail1': ['5.751 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap', 'Jarak Tempuh Rendah', 'Retract Mirror'],
  'price': 'Rp 143.000.000 Rp 2,91 jt/bln',
  'monthly': 'Rp 2,91 jt/bln'},
 {'name': '2020 Daihatsu AYLA R 1.2',
  'detail1': ['15.552 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah'],
  'price': 'Rp 123.000.000 Rp 2,51 jt/bln',
  'monthly': 'Rp 2,51 jt/bln'},
 {'name': '2014 Honda MOBILIO E 1.5',
  'detail1': ['84.575 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 127.000.000 Rp 2,59 jt/bln',
  'monthly': 'Rp 2,59 jt/bln'},
 {'name': '2018 Daihatsu AYLA R 1.2',
  'detail1': ['8.691 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah'],
  'price': 'Rp 106.000.000 Rp 2,16 jt/bln',
  'monthly': 'Rp 2,16 jt/bln'},
 {'name': '2021 Daihatsu TERIOS X DLX 1.5',
  'detail1': ['29.897 km', 'Automatic', 'Depok'],
  'detail2': ['Plat Ganjil', 'Kamera Mundur'],
  'price': 'Rp 207.000.000 Rp 4,22 jt/bln',
  'monthly': 'Rp 4,22 jt/bln'},
 {'name': '2020 Honda BRIO SATYA E 1.2',
  'detail1': ['15.855 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah'],
  'price': 'Rp 147.000.000 Rp 3,00 jt/bln',
  'monthly': 'Rp 3,00 jt/bln'},
 {'name': '2018 Honda HR-V SE 1.5',
  'detail1': ['83.286 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Paddle Shift'],
  'price': 'Rp 257.000.000 Rp 5,24 jt/bln',
  'monthly': 'Rp 5,24 jt/bln'},
 {'name': '2018 Honda BRIO SATYA E 1.2',
  'detail1': ['36.455 km', 'Automatic', 'Jakarta Barat'],
  'detail2': ['Plat Ganjil', 'Sports Mode'],
  'price': 'Rp 139.000.000 Rp 2,83 jt/bln',
  'monthly': 'Rp 2,83 jt/bln'},
 {'name': '2020 Honda BRIO RS 1.2',
  'detail1': ['46.441 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Sports Mode'],
  'price': 'Rp 180.000.000 Rp 3,67 jt/bln',
  'monthly': 'Rp 3,67 jt/bln'},
 {'name': '2016 Toyota FORTUNER VRZ 2.4',
  'detail1': ['94.919 km', 'Automatic', 'Jakarta Selatan'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Power Back Door'],
  'price': 'Rp 365.000.000 Rp 7,44 jt/bln',
  'monthly': 'Rp 7,44 jt/bln'},
 {'name': '2019 Mazda CX-5 ELITE 2.5',
  'detail1': ['45.271 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Genap', 'Auto Retract Mirror', 'Power Back Door'],
  'price': 'Rp 426.000.000 Rp 8,68 jt/bln',
  'monthly': 'Rp 8,68 jt/bln'},
 {'name': '2018 Nissan GRAND LIVINA XV 1.5',
  'detail1': ['98.416 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Ganjil', 'Kamera Mundur'],
  'price': 'Rp 148.000.000 Rp 3,02 jt/bln',
  'monthly': 'Rp 3,02 jt/bln'},
 {'name': '2019 Suzuki ERTIGA GL 1.5',
  'detail1': ['49.988 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 163.000.000 Rp 3,32 jt/bln',
  'monthly': 'Rp 3,32 jt/bln'},
 {'name': '2017 Toyota AGYA G 1.0',
  'detail1': ['78.175 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 99.000.000 Rp 2,02 jt/bln',
  'monthly': 'Rp 2,02 jt/bln'},
 {'name': '2019 Toyota AGYA G TRD 1.2',
  'detail1': ['56.303 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 128.000.000 Rp 2,61 jt/bln',
  'monthly': 'Rp 2,61 jt/bln'},
 {'name': '2021 Suzuki IGNIS GX 1.2',
  'detail1': ['27.044 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Keyless Push Start'],
  'price': 'Rp 148.000.000 Rp 3,02 jt/bln',
  'monthly': 'Rp 3,02 jt/bln'},
 {'name': '2019 Honda HR-V S 1.5',
  'detail1': ['60.978 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 231.000.000 Rp 4,71 jt/bln',
  'monthly': 'Rp 4,71 jt/bln'},
 {'name': '2019 Wuling CORTEZ C T LUX 1.5',
  'detail1': ['55.534 km', 'Automatic', 'Surabaya'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 168.000.000 Rp 3,42 jt/bln',
  'monthly': 'Rp 3,42 jt/bln'},
 {'name': '2021 Wuling ALMAZ RS LT LUX + SC CVT 1.5',
  'detail1': ['38.223 km', 'Automatic', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil', '360 Camera View', 'Panoramic Sun Roof'],
  'price': 'Rp 273.000.000 Rp 5,56 jt/bln',
  'monthly': 'Rp 5,56 jt/bln'},
 {'name': '2019 Wuling CONFERO S 1.5',
  'detail1': ['32.630 km', 'Manual', 'Jakarta Barat'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 104.000.000 Rp 2,12 jt/bln',
  'monthly': 'Rp 2,12 jt/bln'},
 {'name': '2019 Daihatsu AYLA X 1.0',
  'detail1': ['73.528 km', 'Manual', 'Bekasi'],
  'detail2': ['Plat Genap'],
  'price': 'Rp 100.000.000 Rp 2,04 jt/bln',
  'monthly': 'Rp 2,04 jt/bln'},
 {'name': '2019 Wuling ALMAZ L TURBO 1.5',
  'detail1': ['43.439 km', 'Automatic', 'Bekasi'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', '360 Camera View'],
  'price': 'Rp 204.000.000 Rp 4,16 jt/bln',
  'monthly': 'Rp 4,16 jt/bln'},
 {'name': '2019 Daihatsu AYLA R 1.2',
  'detail1': ['25.400 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Ganjil'],
  'price': 'Rp 117.000.000 Rp 2,38 jt/bln',
  'monthly': 'Rp 2,38 jt/bln'},
 {'name': '2017 Toyota KIJANG INNOVA REBORN VENTURER GASOLINE 2.0',
  'detail1': ['89.898 km', 'Automatic', 'Jakarta Utara'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Sports Mode'],
  'price': 'Rp 316.000.000 Rp 6,44 jt/bln',
  'monthly': 'Rp 6,44 jt/bln'},
 {'name': '2014 Toyota AGYA G 1.0',
  'detail1': ['95.007 km', 'Manual', 'Bandung'],
  'detail2': ['Plat Genap', 'Kamera Mundur'],
  'price': 'Rp 87.000.000 Rp 1,77 jt/bln',
  'monthly': 'Rp 1,77 jt/bln'},
 {'name': '2019 Suzuki BALENO HATCHBACK 1.4',
  'detail1': ['72.458 km', 'Automatic', 'Jakarta Timur'],
  'detail2': ['Plat Ganjil', 'Retract Mirror', 'Keyless Push Start'],
  'price': 'Rp 176.000.000 Rp 3,59 jt/bln',
  'monthly': 'Rp 3,59 jt/bln'},
 {'name': '2019 Suzuki BALENO HATCHBACK 1.4',
  'detail1': ['41.091 km', 'Manual', 'Bogor'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Keyless Push Start'],
  'price': 'Rp 160.000.000 Rp 3,26 jt/bln',
  'monthly': 'Rp 3,26 jt/bln'},
 {'name': '2018 Daihatsu AYLA R DLX 1.2',
  'detail1': ['21.880 km', 'Manual', 'Tangerang Selatan'],
  'detail2': ['Plat Ganjil', 'Jarak Tempuh Rendah'],
  'price': 'Rp 114.000.000 Rp 2,32 jt/bln',
  'monthly': 'Rp 2,32 jt/bln'},
 {'name': '2018 Mitsubishi XPANDER ULTIMATE 1.5',
  'detail1': ['66.471 km', 'Automatic', 'Bogor'],
  'detail2': ['Plat Genap', 'Retract Mirror', 'Vehicle Stability Control'],
  'price': 'Rp 209.000.000 Rp 4,26 jt/bln',
  'monthly': 'Rp 4,26 jt/bln'},

In [157]:
df = pd.DataFrame(car, columns=["name", "detail1", "detail2", "price", "monthly"])

In [158]:
df.to_csv("car.csv", index=None)

In [4]:
df = pd.read_csv("car.csv")

In [ ]:
df

,name,detail1,detail2,price,monthly
0,2018 Daihatsu AYLA X 1.2,"['10.508 km', 'Manual', 'Jakarta Utara']","['Plat Genap', 'Jarak Tempuh Rendah']","Rp 101.000.000 Rp 2,06 jt/bln","Rp 2,06 jt/bln"
1,2015 Toyota AGYA TRD SPORTIVO 1.0,"['112.888 km', 'Manual', 'Bogor']",['Plat Genap'],"Rp 82.000.000 Rp 1,67 jt/bln","Rp 1,67 jt/bln"
2,2015 Nissan X-TRAIL 2.5,"['118.429 km', 'Automatic', 'Surabaya']","['Plat Ganjil', '360 Camera View', 'Keyless Pu...","Rp 169.000.000 Rp 3,44 jt/bln","Rp 3,44 jt/bln"
3,2020 Toyota YARIS S TRD 1.5,"['15.945 km', 'Automatic', 'Tangerang Selatan']","['Plat Ganjil', 'Jarak Tempuh Rendah', 'Paddle...","Rp 218.000.000 Rp 4,44 jt/bln","Rp 4,44 jt/bln"
4,2019 Toyota AGYA G 1.2,"['30.404 km', 'Manual', 'Jakarta Barat']",['Plat Ganjil'],"Rp 117.000.000 Rp 2,38 jt/bln","Rp 2,38 jt/bln"
...,...,...,...,...,...
605,2021 Toyota RAIZE GR SPORT TSS 1.0,"['32.288 km', 'Automatic', 'Bogor']","['Plat Ganjil', 'Auto Retract Mirror', 'Paddle...","Rp 234.000.000 Rp 4,77 jt/bln","Rp 4,77 jt/bln"
606,2019 Toyota AGYA G TRD 1.2,"['26.474 km', 'Automatic', 'Jakarta Utara']",['Plat Ganjil'],"Rp 136.000.000 Rp 2,77 jt/bln","Rp 2,77 jt/bln"
607,2022 Hyundai STARGAZER PRIME 1.5,"['2.651 km', 'Automatic', 'Bogor']","['Plat Genap', 'Jarak Tempuh Rendah', 'Retract...","Rp 246.000.000 Rp 5,01 jt/bln","Rp 5,01 jt/bln"
608,2017 Toyota CALYA G 1.2,"['34.349 km', 'Manual', 'Jakarta Utara']",['Plat Genap'],"Rp 116.000.000 Rp 2,36 jt/bln","Rp 2,36 jt/bln"
609,2017 Daihatsu XENIA R SPORTY 1.3,"['90.740 km', 'Manual', 'Bogor']","['Plat Genap', 'Kamera Mundur']","Rp 149.000.000 Rp 3,04 jt/bln","Rp 3,04 jt/bln"

In [ ]:
df['price'] = df['price'].astype('object')
df['monthly'] = df['monthly'].astype('object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     610 non-null    object
 1   detail1  610 non-null    object
 2   detail2  610 non-null    object
 3   price    610 non-null    object
 4   monthly  610 non-null    object
dtypes: object(5)
memory usage: 24.0+ KB

In [ ]:
df

,name,detail1,detail2,price,monthly
0,2018 Daihatsu AYLA X 1.2,"['10.508 km', 'Manual', 'Jakarta Utara']","['Plat Genap', 'Jarak Tempuh Rendah']","Rp 101.000.000 Rp 2,06 jt/bln","Rp 2,06 jt/bln"
1,2015 Toyota AGYA TRD SPORTIVO 1.0,"['112.888 km', 'Manual', 'Bogor']",['Plat Genap'],"Rp 82.000.000 Rp 1,67 jt/bln","Rp 1,67 jt/bln"
2,2015 Nissan X-TRAIL 2.5,"['118.429 km', 'Automatic', 'Surabaya']","['Plat Ganjil', '360 Camera View', 'Keyless Pu...","Rp 169.000.000 Rp 3,44 jt/bln","Rp 3,44 jt/bln"
3,2020 Toyota YARIS S TRD 1.5,"['15.945 km', 'Automatic', 'Tangerang Selatan']","['Plat Ganjil', 'Jarak Tempuh Rendah', 'Paddle...","Rp 218.000.000 Rp 4,44 jt/bln","Rp 4,44 jt/bln"
4,2019 Toyota AGYA G 1.2,"['30.404 km', 'Manual', 'Jakarta Barat']",['Plat Ganjil'],"Rp 117.000.000 Rp 2,38 jt/bln","Rp 2,38 jt/bln"
...,...,...,...,...,...
605,2021 Toyota RAIZE GR SPORT TSS 1.0,"['32.288 km', 'Automatic', 'Bogor']","['Plat Ganjil', 'Auto Retract Mirror', 'Paddle...","Rp 234.000.000 Rp 4,77 jt/bln","Rp 4,77 jt/bln"
606,2019 Toyota AGYA G TRD 1.2,"['26.474 km', 'Automatic', 'Jakarta Utara']",['Plat Ganjil'],"Rp 136.000.000 Rp 2,77 jt/bln","Rp 2,77 jt/bln"
607,2022 Hyundai STARGAZER PRIME 1.5,"['2.651 km', 'Automatic', 'Bogor']","['Plat Genap', 'Jarak Tempuh Rendah', 'Retract...","Rp 246.000.000 Rp 5,01 jt/bln","Rp 5,01 jt/bln"
608,2017 Toyota CALYA G 1.2,"['34.349 km', 'Manual', 'Jakarta Utara']",['Plat Genap'],"Rp 116.000.000 Rp 2,36 jt/bln","Rp 2,36 jt/bln"
609,2017 Daihatsu XENIA R SPORTY 1.3,"['90.740 km', 'Manual', 'Bogor']","['Plat Genap', 'Kamera Mundur']","Rp 149.000.000 Rp 3,04 jt/bln","Rp 3,04 jt/bln"

In [ ]:
df.to_excel('car.xlsx', index=False)

In [ ]:
max_length = df.applymap(len).max()

print("Maximum length of arrays in the DataFrame:", max_length)

Maximum length of arrays in the DataFrame: name       54
detail1    48
detail2    67
price      30
monthly    15
dtype: int64

In [ ]:
#title_list = [title.text.strip() for title in titles]
#price_list = [str(whole.get_text(strip=True)) + str(fraction.get_text(strip=True)) for whole, fraction in zip(price_whole, price_fraction)]
#rating_list = [x.text.strip() for x in rating]